name: "Get CI"

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - '*'

jobs:
  macos-run-tests:
    name: Unit Tests (Xcode ${{ matrix.xcode }})
    strategy:
      fail-fast: false
      matrix:
        xcode: ["15.0", "15.3"]
        include:
          - xcode: "15.3"
            macos: macOS-14
          - xcode: "15.0"
            macos: macOS-14
    runs-on: ${{ matrix.macos }}
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: swift test

  linux-run-tests:
    name: Unit Tests (Linux, Swift ${{ matrix.swift }})
    strategy:
      fail-fast: false
      matrix:
        swift: ["5.9"]
    runs-on: ubuntu-latest
    container: swift:${{ matrix.swift }}
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: swift test

  discover-typos:
    name: Discover Typos
    runs-on: macOS-14
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.3.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Discover typos
        run: |
          export PATH="$PATH:/Library/Frameworks/Python.framework/Versions/3.12/bin"
          python3 -m pip install --upgrade pip
          python3 -m pip install codespell
          codespell --ignore-words-list="hart,inout,msdos,sur" --skip="./.build/*,./Tests/GetTests/Mocker/*,./.git/*"
